# Generated by Django 5.2 on 2025-04-15 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_category_description_alter_category_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='title',
        ),
    ]
