# Generated by Django 5.2 on 2025-04-20 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_participant_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='event',
            new_name='events',
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.category'),
        ),
    ]
